"""initial migration

Revision ID: d0c2a40272e4
Revises: 
Create Date: 2026-06-18 00:37:22.172120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c2a40272e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impressions',
    sa.Column('impression_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('bid_price', sa.Float(), nullable=False),
    sa.Column('ctr_score', sa.Float(), nullable=False),
    sa.Column('synergy_score', sa.Float(), nullable=False),
    sa.Column('bid_model_version', sa.String(), nullable=False),
    sa.Column('creative_model_version', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('impression_id')
    )
    op.create_index(op.f('ix_impressions_impression_id'), 'impressions', ['impression_id'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('impression_id', sa.String(), nullable=False),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['impression_id'], ['impressions.impression_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomes_id'), 'outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_outcomes_impression_id'), 'outcomes', ['impression_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcomes_impression_id'), table_name='outcomes')
    op.drop_index(op.f('ix_outcomes_id'), table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_impressions_impression_id'), table_name='impressions')
    op.drop_table('impressions')
    # ### end Alembic commands ###
